# Generated by Django 5.2.6 on 2025-10-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_absence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
