# Generated by Django 5.2.6 on 2025-10-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_classroom_profile_is_teacher_checklistitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
