# Generated by Django 5.2.6 on 2025-12-14 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_prayerstar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('prayer', models.IntegerField(choices=[(1, 'الفجر'), (2, 'الظهر'), (3, 'العصر'), (4, 'المغرب'), (5, 'العشاء')])),
                ('prayed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date', 'prayer')},
            },
        ),
        migrations.DeleteModel(
            name='PrayerStar',
        ),
    ]
