# Generated by Django 5.2.6 on 2026-02-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_quizscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zeugnis_link',
            field=models.URLField(blank=True, null=True, verbose_name='Zeugnis 1. Schulhalbjahr'),
        ),
        migrations.AlterField(
            model_name='ramadanitemdone',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ramadanitemdone',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ramadanitemdone',
            name='item_key',
            field=models.CharField(max_length=50),
        ),
    ]
