# Generated by Django 5.2.6 on 2026-02-01 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_quizscore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_teacher',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='profile',
            name='zeugnis_link',
            field=models.URLField(blank=True, null=True, verbose_name='Zeugnis 1. Schulhalbjahr'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ramadanitemdone',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ramadanitemdone',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ramadanitemdone',
            name='item_key',
            field=models.CharField(max_length=50),
        ),
    ]
