# Generated by Django 5.2.6 on 2026-02-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profile_classroom_profile_groups_profile_is_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_teacher',
        ),
    ]
