# Generated by Django 5.2.6 on 2026-09-14 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_teacherpointaward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_competitions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LiveCompetitionGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('live', 'Läuft'), ('finished', 'Beendet')], default='live', max_length=12)),
                ('current_question_index', models.PositiveIntegerField(default=0)),
                ('team_a_score', models.PositiveIntegerField(default=0)),
                ('team_b_score', models.PositiveIntegerField(default=0)),
                ('winner', models.CharField(blank=True, choices=[('A', 'Gruppe A'), ('B', 'Gruppe B')], max_length=1)),
                ('winner_points_awarded', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='core.livecompetition')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_games_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LiveCompetitionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Frage')),
                ('option_1', models.CharField(max_length=300, verbose_name='Antwort 1')),
                ('option_2', models.CharField(max_length=300, verbose_name='Antwort 2')),
                ('option_3', models.CharField(max_length=300, verbose_name='Antwort 3')),
                ('option_4', models.CharField(max_length=300, verbose_name='Antwort 4')),
                ('correct_option', models.PositiveSmallIntegerField(choices=[(1, 'Antwort 1'), (2, 'Antwort 2'), (3, 'Antwort 3'), (4, 'Antwort 4')])),
                ('order', models.PositiveIntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.livecompetition')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LiveCompetitionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('A', 'Gruppe A'), ('B', 'Gruppe B')], max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.livecompetitiongame')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_competition_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game', 'student'), name='unique_live_game_student')],
            },
        ),
        migrations.CreateModel(
            name='LiveCompetitionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('A', 'Gruppe A'), ('B', 'Gruppe B')], max_length=1)),
                ('selected_option', models.PositiveSmallIntegerField(choices=[(1, 'Antwort 1'), (2, 'Antwort 2'), (3, 'Antwort 3'), (4, 'Antwort 4')])),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.livecompetitiongame')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_answers', to='core.livecompetitionquestion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game', 'question'), name='unique_live_game_question_answer')],
            },
        ),
    ]
