# Generated by Django 5.2.6 on 2026-09-14 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_livecompetition_livecompetitiongame_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuranReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portion_index', models.PositiveSmallIntegerField()),
                ('completed_on', models.DateField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quran_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-completed_on', '-completed_at'),
                'constraints': [models.UniqueConstraint(fields=('student', 'completed_on'), name='unique_daily_quran_reading'), models.UniqueConstraint(fields=('student', 'portion_index'), name='unique_student_quran_portion')],
            },
        ),
    ]
