# Generated by Django 5.2.6 on 2026-09-24 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_dailyquranreading'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPointActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('assignment', 'Hausaufgabe'), ('prayer', 'Gebetstag'), ('ramadan', 'Ramadan-Tag'), ('library', 'Bibliothek'), ('quran', 'Koranlesung')], max_length=20)),
                ('source_key', models.CharField(max_length=100)),
                ('activity_date', models.DateField()),
                ('label_ar', models.CharField(max_length=300)),
                ('label_de', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Wartet auf Eltern'), ('confirmed', 'Bestätigt'), ('rejected', 'Entfernt'), ('expired', 'Abgelaufen')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-activity_date', '-created_at', '-id'),
                'indexes': [models.Index(fields=['student', 'status', 'activity_date'], name='core_studen_student_30a3e1_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'category', 'source_key'), name='unique_student_point_activity')],
            },
        ),
    ]
