# Generated by Django 5.2.6 on 2026-09-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_parentapprovalcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='also_show_in_2027',
            field=models.BooleanField(default=False, help_text='Alte Einträge bleiben in 2025/2026 erhalten und werden zusätzlich in 2026/2027 angezeigt.', verbose_name='Auch im Schuljahr 2026/2027 anzeigen'),
        ),
    ]
