# Generated by Django 5.2.6 on 2026-09-25 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_checklistitem_also_show_in_2027'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentchecklist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentchecklist',
            name='school_year',
            field=models.CharField(choices=[('2026', 'Schuljahr 2025/2026'), ('2027', 'Schuljahr 2026/2027')], default='2026', max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name='studentchecklist',
            unique_together={('student', 'item', 'school_year')},
        ),
    ]
